title: Forecasting and Risk Analysis (BANA 4090)
description: By Jiantong Wang (wang5jt@mail.uc.edu)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false